[database]
host = "ep-green-breeze-at9hxpbl-pooler.c-9.us-east-1.aws.neon.tech"
port = 5432
name = "neondb"
user = "neondb_owner"
password = "npg_TvdFLCn29DoZ"

[api]
groq_key = "your_groq_api_key_here"
